# Travis config for EMA workbench
language: python
sudo: false

python:
- 2.7

env:
- DEPS="numpy=1.8 matplotlib=1.3 jinja2=2.7.2 pandas=0.13.1 ipython nose scikit-learn mock pydot"

install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install -c conda conda-env
- conda update -q conda --no-deps
- conda info -a # Useful for debugging any issues with conda
- conda install --yes $DEPS # Replace dep1 dep2 ... with your dependencies
- pip install deap # deap is another dependency, not available via conda
- pip install zmq # zmq is not available via conda for some reason
# jpype installation code to be added

script:
- nosetests

# coverage needs to be added
# after_success:
# - coveralls

notifications:
email: false