# Travis config for EMA workbench
language: python

python:
  - 2.7

envs:
  - DEPS="numpy=1.8 matplotlib scipy pandas"
  - DEAP_VERSION=1.02

install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
else
wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install -c conda conda-env
- conda update -q conda --no-deps
# Useful for debugging any issues with conda
- conda info -a

# Replace dep1 dep2 ... with your dependencies
- conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION $DEPS pip
- pip install deap=$DEAP_VERSION

# script:
# here goes the command that initiates all the tests

# coverage needs to be added
# after_success:
# - coveralls

notifications:
email: false